### PR TITLE
[FIX] fixes the double underscore problem and adds estimates.json support

### PR DESCRIPTION
**Pull request by noahbenson**
This fixes most of the bugs discussed in issue #22 and adds support for the JSON files, which seems to work so far.

This doesn't fix the config.json issue yet.

### CODE REVIEW

**Comment by noahbenson** [comment]
@garikoitz can you explain the issue with the config.json file again? How did you end up with a config.json directory?

Also, just to make sure I understand, for aprf, what should the default config file be named when no config file is found? prfanalyze-aprf-default-config.json?

**Comment by garikoitz** [comment]
If there is no valid json it should write it in the $OUTPUT directory,
where the BIDS directory is
thanks! will get back to it later

**Comment by garikoitz** [comment]
I don't know how to make it throw a default config json. I am running the gear and the json files is not there and there is no message whatsoever

**Comment by noahbenson** [comment]
Ahh, I see what happened--it was trying to write it in the input directory. I just pushed a fix and will make a new PR.

**Pull request merged**
