### PR TITLE
Update prfsynth-config_sub-ellipse_ses-tr1dur300v3.json

### PR DESCRIPTION
**Pull request by DantePk420**

### CODE REVIEW

**Comment by DantePk420** [comment]
Please do accept this merge

**Comment by wandell** [comment]
Gari to check.

Thanks,
Brian

From: Dante ***@***.***>
Date: Wednesday, August 23, 2023 at 1:11 PM
To: vistalab/PRFmodel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [vistalab/PRFmodel] Update prfsynth-config_sub-ellipse_ses-tr1dur300v3.json (PR #94)

Please do accept this merge

**Comment by garikoitz** [comment]
Hi Dante,
is your only change to go from parallel true to false?
but you don't need to do a PR for this, right? why don't just edit it and
use it with the False just in your fork?
On top of that, we usually make copies of configs per project, outside of
the repo.
Maybe I am missing something, please let me know.
thanks!
Gari

**Comment by DantePk420** [comment]
I am sorry you don’t have to my bad

**Pull request closed without merging**
