### PR TITLE
Temporal feature3

### PR DESCRIPTION
**Pull request by KimInsub**
1) added temporal processing related files
2) pmStimulus: fixed Y grid
3) pmTemporal:  code clean up

### CODE REVIEW

**Comment by elinekupers** [comment]
I think we already have certain functions in the general "functions" folder! Unless you are organizing the content of this folder we should be careful not making duplicates! 

Also, I don't think we need stigliani's entire model library since we only use a couple functions..

**Comment by garikoitz** [comment]
ok so should I wait for a new PR? I will merge it this weekend

**Comment by elinekupers** [comment]
Sorry, I thought this was for a different repository Insub and I are also working on! Please disregard my comment!

**Comment by garikoitz** [comment]
ah! ok :)

Insub, I will look it this weekend

**Comment by garikoitz** [comment]
this is old now, Insub says to close it, he has newer branches

**Pull request closed without merging**
