### PR TITLE
prfanalyze in a docker

### PR DESCRIPTION
**Pull request by noahbenson**
This pull request adds a prfanalyze docker in the 'gear' directory.

### CODE REVIEW

**Comment by noahbenson** [comment]
I'm still testing some things with vista and afni, so I may need to amend this in a bit, but aprf should be fine and should produce basically the same outputs as vista. You'll have to edit the compile.sh scripts and/or make copies to get them to work possibly (sorry about that!)

**Comment by garikoitz** [comment]
I didn't get that, I use the compile_black_gari.sh script for prfsynth, I
can create a version of it to compile those?
so, can I git pull, compile and test now?

**Comment by noahbenson** [comment]
Yep! Go ahead; I may add more pull requests as I find bugs!

**Comment by noahbenson** [comment]
Hmm, when I recompile with the current version and the updated vistasoft hook, I still seem to be getting the mrInit error we talked about earlier... let me know if you get it (it might be my configuration)

**Comment by garikoitz** [comment]
ok, so first I compile prfsynth or I forget about it for now?

**Comment by noahbenson** [comment]
you don't have to compile it for the others to work, but yeah, prfsynth should be working, including AFNI HRFs. The popeye hrf only works for the builtin TR values.

**Comment by garikoitz** [comment]
ok! I start with the analyze ones then

**Pull request merged**
